import type { Diagnosis, Patient, Vitals } from '@mednexus/shared/types';

function vitals(base: Partial<Vitals> = {}): Vitals {
  return {
    bloodPressure: '118/76',
    heartRate: 74,
    temperature: 98.4,
    oxygenSaturation: 97,
    weight: 72,
    height: 175,
    recordedAt: new Date().toISOString(),
    ...base,
  };
}

function diagnosis(
  id: string,
  condition: string,
  diagnosedAt: string
): Diagnosis {
  return {
    id,
    condition,
    icdCode: 'Z00.00',
    diagnosedAt,
    doctor: 'Dr. A. Patel',
  };
}

/** Mock registry: only `Patient` records; dashboard metrics are derived at runtime. */
export const mockPatients: Patient[] = (() => {
  const now = new Date();
  const atDaysAgo = (days: number, hour = 10, minute = 20) => {
    const d = new Date(now);
    d.setDate(d.getDate() - days);
    d.setHours(hour, minute, 0, 0);
    return d.toISOString();
  };

  const todayYmd = now.toISOString().slice(0, 10);

  const p = (
    partial: Omit<Patient, 'vitals' | 'appointments'> & {
      vitals?: Vitals;
    }
  ): Patient => ({
    ...partial,
    vitals: partial.vitals ?? vitals(),
    appointments: [],
  });

  return [
    p({
      id: 'P-88293',
      firstName: 'Elena',
      lastName: 'Kostic',
      dateOfBirth: '1983-04-12',
      gender: 'female',
      bloodGroup: 'A+',
      email: 'elena.k@example.com',
      phone: '+1-555-0101',
      address: '12 Oak St',
      status: 'stable',
      department: 'Cardiology',
      assignedDoctor: 'Dr. Chen',
      admittedAt: atDaysAgo(2, 11, 20),
      diagnoses: [
        diagnosis('dx-1', 'Post-Operative Recovery (Cardiac)', atDaysAgo(2)),
      ],
    }),
    p({
      id: 'P-91022',
      firstName: 'Marcus',
      lastName: 'Benning',
      dateOfBirth: '1958-07-03',
      gender: 'male',
      bloodGroup: 'O+',
      email: 'marcus.b@example.com',
      phone: '+1-555-0102',
      address: '44 Pine Rd',
      status: 'critical',
      department: 'Cardiology',
      assignedDoctor: 'Dr. Chen',
      admittedAt: atDaysAgo(1, 4, 15),
      diagnoses: [
        diagnosis('dx-2', 'Acute Myocardial Infarction', atDaysAgo(1)),
      ],
      vitals: vitals({ heartRate: 112, oxygenSaturation: 91 }),
    }),
    p({
      id: 'P-77121',
      firstName: 'Julianna',
      lastName: 'Lowe',
      dateOfBirth: '1996-11-22',
      gender: 'female',
      bloodGroup: 'B+',
      email: 'julianna.l@example.com',
      phone: '+1-555-0103',
      address: '9 Elm Ave',
      status: 'observation',
      department: 'Orthopedics',
      assignedDoctor: 'Dr. Ortiz',
      admittedAt: atDaysAgo(1, 23, 55),
      diagnoses: [
        diagnosis('dx-3', 'Tibial Compound Fracture', atDaysAgo(1)),
      ],
    }),
    p({
      id: 'P-66122',
      firstName: 'Arthur',
      lastName: 'Pendelton',
      dateOfBirth: '1970-02-18',
      gender: 'male',
      bloodGroup: 'AB+',
      email: 'arthur.p@example.com',
      phone: '+1-555-0104',
      address: '3 Maple Ln',
      status: 'stable',
      department: 'General Medicine',
      assignedDoctor: 'Dr. Singh',
      admittedAt: atDaysAgo(1, 8, 30),
      diagnoses: [diagnosis('dx-4', 'Pneumonia', atDaysAgo(1))],
    }),
    p({
      id: 'P-55219',
      firstName: 'Sarah',
      lastName: 'Connor',
      dateOfBirth: '1992-09-05',
      gender: 'female',
      bloodGroup: 'O-',
      email: 'sarah.c@example.com',
      phone: '+1-555-0105',
      address: '77 Cedar Ct',
      status: 'stable',
      department: 'General Surgery',
      assignedDoctor: 'Dr. Kim',
      admittedAt: atDaysAgo(0, 14, 0),
      diagnoses: [diagnosis('dx-5', 'Appendicitis', atDaysAgo(0))],
    }),
    p({
      id: 'P-44001',
      firstName: 'James',
      lastName: 'Wu',
      dateOfBirth: '1965-12-01',
      gender: 'male',
      bloodGroup: 'A-',
      email: 'james.w@example.com',
      phone: '+1-555-0106',
      address: '21 Birch Way',
      status: 'active',
      department: 'Neurology',
      assignedDoctor: 'Dr. Rao',
      admittedAt: atDaysAgo(3, 9, 0),
      diagnoses: [diagnosis('dx-6', 'Transient Ischemic Attack', atDaysAgo(3))],
    }),
    p({
      id: 'P-44002',
      firstName: 'Priya',
      lastName: 'Nair',
      dateOfBirth: '1988-05-14',
      gender: 'female',
      bloodGroup: 'B-',
      email: 'priya.n@example.com',
      phone: '+1-555-0107',
      address: '5 Spruce Dr',
      status: 'stable',
      department: 'Neurology',
      assignedDoctor: 'Dr. Rao',
      admittedAt: atDaysAgo(4, 16, 40),
      diagnoses: [diagnosis('dx-7', 'Migraine with Aura', atDaysAgo(4))],
    }),
    p({
      id: 'P-44003',
      firstName: 'Omar',
      lastName: 'Haddad',
      dateOfBirth: '1979-08-29',
      gender: 'male',
      bloodGroup: 'AB-',
      email: 'omar.h@example.com',
      phone: '+1-555-0108',
      address: '90 Lake St',
      status: 'critical',
      department: 'Emergency',
      assignedDoctor: 'Dr. Flores',
      admittedAt: atDaysAgo(0, 2, 10),
      diagnoses: [diagnosis('dx-8', 'Sepsis — suspected', atDaysAgo(0))],
      vitals: vitals({ temperature: 101.2, heartRate: 118 }),
    }),
    p({
      id: 'P-44004',
      firstName: 'Linda',
      lastName: 'Martinez',
      dateOfBirth: '1954-03-07',
      gender: 'female',
      bloodGroup: 'O+',
      email: 'linda.m@example.com',
      phone: '+1-555-0109',
      address: '33 Hill Rd',
      status: 'discharged',
      department: 'Orthopedics',
      assignedDoctor: 'Dr. Ortiz',
      admittedAt: atDaysAgo(5, 12, 0),
      dischargedAt: `${todayYmd}T15:30:00.000Z`,
      diagnoses: [diagnosis('dx-9', 'Hip Replacement — follow-up', atDaysAgo(5))],
    }),
    p({
      id: 'P-44005',
      firstName: 'Kevin',
      lastName: 'Osei',
      dateOfBirth: '2001-01-30',
      gender: 'male',
      bloodGroup: 'A+',
      email: 'kevin.o@example.com',
      phone: '+1-555-0110',
      address: '18 River Rd',
      status: 'discharged',
      department: 'General Medicine',
      assignedDoctor: 'Dr. Singh',
      admittedAt: atDaysAgo(6, 8, 45),
      dischargedAt: `${todayYmd}T09:00:00.000Z`,
      diagnoses: [diagnosis('dx-10', 'Influenza A', atDaysAgo(6))],
    }),
    p({
      id: 'P-44006',
      firstName: 'Mei',
      lastName: 'Zhang',
      dateOfBirth: '1990-06-21',
      gender: 'female',
      bloodGroup: 'B+',
      email: 'mei.z@example.com',
      phone: '+1-555-0111',
      address: '2 Garden Pl',
      status: 'observation',
      department: 'Cardiology',
      assignedDoctor: 'Dr. Chen',
      admittedAt: atDaysAgo(5, 19, 10),
      diagnoses: [
        diagnosis('dx-11', 'Atrial Fibrillation — new onset', atDaysAgo(5)),
      ],
    }),
    p({
      id: 'P-44007',
      firstName: 'Diego',
      lastName: 'Salinas',
      dateOfBirth: '1972-10-11',
      gender: 'male',
      bloodGroup: 'O+',
      email: 'diego.s@example.com',
      phone: '+1-555-0112',
      address: '60 Coast Hwy',
      status: 'stable',
      department: 'Orthopedics',
      assignedDoctor: 'Dr. Ortiz',
      admittedAt: atDaysAgo(6, 14, 20),
      diagnoses: [diagnosis('dx-12', 'Rotator Cuff Tear', atDaysAgo(6))],
    }),
    p({
      id: 'P-44008',
      firstName: 'Fatima',
      lastName: 'Rahman',
      dateOfBirth: '1985-02-02',
      gender: 'female',
      bloodGroup: 'A+',
      email: 'fatima.r@example.com',
      phone: '+1-555-0113',
      address: '14 Market St',
      status: 'active',
      department: 'General Surgery',
      assignedDoctor: 'Dr. Kim',
      admittedAt: atDaysAgo(2, 7, 15),
      diagnoses: [diagnosis('dx-13', 'Cholecystitis', atDaysAgo(2))],
    }),
    p({
      id: 'P-44009',
      firstName: 'Noah',
      lastName: 'Berg',
      dateOfBirth: '1999-12-19',
      gender: 'male',
      bloodGroup: 'B+',
      email: 'noah.b@example.com',
      phone: '+1-555-0114',
      address: '8 Summit Tr',
      status: 'stable',
      department: 'Emergency',
      assignedDoctor: 'Dr. Flores',
      admittedAt: atDaysAgo(3, 22, 5),
      diagnoses: [diagnosis('dx-14', 'Laceration — repaired', atDaysAgo(3))],
    }),
    p({
      id: 'P-44010',
      firstName: 'Aisha',
      lastName: 'Diallo',
      dateOfBirth: '1977-07-25',
      gender: 'female',
      bloodGroup: 'O-',
      email: 'aisha.d@example.com',
      phone: '+1-555-0115',
      address: '41 Valley Rd',
      status: 'critical',
      department: 'Neurology',
      assignedDoctor: 'Dr. Rao',
      admittedAt: atDaysAgo(0, 6, 0),
      diagnoses: [diagnosis('dx-15', 'Subdural Hematoma — monitoring', atDaysAgo(0))],
      vitals: vitals({ bloodPressure: '160/95', heartRate: 98 }),
    }),
    p({
      id: 'P-44011',
      firstName: 'Tom',
      lastName: 'Hughes',
      dateOfBirth: '1961-04-08',
      gender: 'male',
      bloodGroup: 'A-',
      email: 'tom.h@example.com',
      phone: '+1-555-0116',
      address: '55 Field Ln',
      status: 'stable',
      department: 'General Medicine',
      assignedDoctor: 'Dr. Singh',
      admittedAt: atDaysAgo(4, 11, 50),
      diagnoses: [diagnosis('dx-16', 'COPD Exacerbation', atDaysAgo(4))],
    }),
    p({
      id: 'P-44012',
      firstName: 'Rosa',
      lastName: 'Vega',
      dateOfBirth: '1993-11-30',
      gender: 'female',
      bloodGroup: 'AB+',
      email: 'rosa.v@example.com',
      phone: '+1-555-0117',
      address: '7 Harbor View',
      status: 'active',
      department: 'Cardiology',
      assignedDoctor: 'Dr. Chen',
      admittedAt: atDaysAgo(5, 6, 25),
      diagnoses: [diagnosis('dx-17', 'Heart Failure — compensated', atDaysAgo(5))],
    }),
    p({
      id: 'P-44013',
      firstName: 'Henry',
      lastName: 'Okonkwo',
      dateOfBirth: '1950-09-17',
      gender: 'male',
      bloodGroup: 'O+',
      email: 'henry.o@example.com',
      phone: '+1-555-0118',
      address: '22 Station Rd',
      status: 'discharged',
      department: 'Emergency',
      assignedDoctor: 'Dr. Flores',
      admittedAt: atDaysAgo(7, 18, 0),
      dischargedAt: `${todayYmd}T11:45:00.000Z`,
      diagnoses: [diagnosis('dx-18', 'Dehydration', atDaysAgo(7))],
    }),
    p({
      id: 'P-44014',
      firstName: 'Chloe',
      lastName: 'Dubois',
      dateOfBirth: '2004-06-03',
      gender: 'female',
      bloodGroup: 'A+',
      email: 'chloe.d@example.com',
      phone: '+1-555-0119',
      address: '11 Rue Lane',
      status: 'observation',
      department: 'General Surgery',
      assignedDoctor: 'Dr. Kim',
      admittedAt: atDaysAgo(0, 18, 30),
      diagnoses: [diagnosis('dx-19', 'Post-Op Nausea', atDaysAgo(0))],
    }),
  ];
})();
